--------------------------------------------------------
--  File created - Friday-March-30-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table VOFFICE_SIGN_HISTORY
--------------------------------------------------------

  CREATE TABLE "QLDV_VOFFICE_SIGN_HISTORY" ("VO_SH_ID" NUMBER, "VO_SH_STATEMENT_ID" NUMBER, "VO_SH_TRANS_CODE" VARCHAR2(200), "VO_SH_RESULT_CODE" NUMBER, "VO_SH_CREATE_DATE" DATE) ;

   COMMENT ON COLUMN "QLDV_VOFFICE_SIGN_HISTORY"."VO_SH_ID" IS 'ID CUA BANG';
   COMMENT ON COLUMN "QLDV_VOFFICE_SIGN_HISTORY"."VO_SH_STATEMENT_ID" IS 'STATEMENT ID';
   COMMENT ON COLUMN "QLDV_VOFFICE_SIGN_HISTORY"."VO_SH_TRANS_CODE" IS 'TRANSACTION CODE SEND TO VOFFICE';
   COMMENT ON COLUMN "QLDV_VOFFICE_SIGN_HISTORY"."VO_SH_RESULT_CODE" IS 'VOFFICE SIGN RESULT CODE';
   COMMENT ON COLUMN "QLDV_VOFFICE_SIGN_HISTORY"."VO_SH_CREATE_DATE" IS 'CREATE DATE';
--------------------------------------------------------
--  DDL for Index VOFFICE_SIGN_HISTORY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "QLDV_VOFFICE_SIGN_HISTORY_PK" ON "QLDV_VOFFICE_SIGN_HISTORY" ("VO_SH_ID");
--------------------------------------------------------
--  Constraints for Table VOFFICE_SIGN_HISTORY
--------------------------------------------------------

  ALTER TABLE "QLDV_VOFFICE_SIGN_HISTORY" MODIFY ("VO_SH_ID" NOT NULL ENABLE);
  ALTER TABLE "QLDV_VOFFICE_SIGN_HISTORY" MODIFY ("VO_SH_STATEMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "QLDV_VOFFICE_SIGN_HISTORY" MODIFY ("VO_SH_TRANS_CODE" NOT NULL ENABLE);
  ALTER TABLE "QLDV_VOFFICE_SIGN_HISTORY" ADD CONSTRAINT "QLDV_VOFFICE_SIGN_HISTORY_PK" PRIMARY KEY ("VO_SH_ID") USING INDEX  ENABLE;
