--------------------------------------------------------
--  File created - Friday-March-30-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table UNIONS_MEMBER
--------------------------------------------------------

  CREATE TABLE "QLDV_UNIONS_MEMBER" ("UNION_MEMBER_ID" NUMBER, "UNION_ID" NUMBER, "FULL_NAME" VARCHAR2(200), "NATIONAL_ID" VARCHAR2(50), "MEMBER_TYPE" VARCHAR2(50), "MEMBER_ID" VARCHAR2(50), "LAPTOP_ID" VARCHAR2(50), "BAR_CODE_PRINT" NUMBER, "APPR_STATUS1" VARCHAR2(1), "APPR_USER1" VARCHAR2(50), "APPR_DATE1" TIMESTAMP (6), "APPR_STATUS2" VARCHAR2(1), "APPR_USER2" VARCHAR2(50), "APPR_DATE2" TIMESTAMP (6), "APPR_STATUS3" VARCHAR2(1), "APPR_USER3" VARCHAR2(50), "APPR_DATE3" TIMESTAMP (6), "APPR_STATUS" VARCHAR2(1), "CREATE_USER" VARCHAR2(50), "CREATE_DATE" TIMESTAMP (6), "UPDATE_USER" VARCHAR2(50), "UPDATE_DATE" TIMESTAMP (6), "REASON_NOT_APP" VARCHAR2(500), "BAR_CODE_USER" VARCHAR2(20), "BAR_CODE_COMPUTER" VARCHAR2(20)) ;

   COMMENT ON COLUMN "QLDV_UNIONS_MEMBER"."UNION_MEMBER_ID" IS 'ID của bảng';
   COMMENT ON COLUMN "QLDV_UNIONS_MEMBER"."UNION_ID" IS 'ID đoàn';
   COMMENT ON COLUMN "QLDV_UNIONS_MEMBER"."FULL_NAME" IS 'Họ tên';
   COMMENT ON COLUMN "QLDV_UNIONS_MEMBER"."NATIONAL_ID" IS 'ID quốc tịch';
   COMMENT ON COLUMN "QLDV_UNIONS_MEMBER"."MEMBER_TYPE" IS 'Loại đối tác';
   COMMENT ON COLUMN "QLDV_UNIONS_MEMBER"."MEMBER_ID" IS 'CMND/Hộ chiếu/Mã nhân viên';
   COMMENT ON COLUMN "QLDV_UNIONS_MEMBER"."LAPTOP_ID" IS 'Seri máy tính';
   COMMENT ON COLUMN "QLDV_UNIONS_MEMBER"."BAR_CODE_PRINT" IS 'Số lần in mã vạch';
   COMMENT ON COLUMN "QLDV_UNIONS_MEMBER"."APPR_STATUS1" IS 'Trạng thái phê duyệt (A: Approve, R: Refused) mức 1';
   COMMENT ON COLUMN "QLDV_UNIONS_MEMBER"."APPR_USER1" IS 'Người phê duyệt cấp 1';
   COMMENT ON COLUMN "QLDV_UNIONS_MEMBER"."APPR_DATE1" IS 'Thời gian phê duyệt cấp 1';
   COMMENT ON COLUMN "QLDV_UNIONS_MEMBER"."APPR_STATUS2" IS 'Trạng thái phê duyệt (A: Approve, R: Refused) mức 2';
   COMMENT ON COLUMN "QLDV_UNIONS_MEMBER"."APPR_USER2" IS 'Người phê duyệt cấp 2';
   COMMENT ON COLUMN "QLDV_UNIONS_MEMBER"."APPR_DATE2" IS 'Thời gian phê duyệt cấp 2';
   COMMENT ON COLUMN "QLDV_UNIONS_MEMBER"."APPR_STATUS3" IS 'Trạng thái phê duyệt (A: Approve, R: Refused) mức 3';
   COMMENT ON COLUMN "QLDV_UNIONS_MEMBER"."APPR_USER3" IS 'Người phê duyệt cấp 3';
   COMMENT ON COLUMN "QLDV_UNIONS_MEMBER"."APPR_DATE3" IS 'Thời gian phê duyệt cấp 3';
   COMMENT ON COLUMN "QLDV_UNIONS_MEMBER"."APPR_STATUS" IS 'Trạng thái phê duyệt cuối cùng (A: Approve, R: Refused)';
   COMMENT ON COLUMN "QLDV_UNIONS_MEMBER"."CREATE_USER" IS 'Người tạo';
   COMMENT ON COLUMN "QLDV_UNIONS_MEMBER"."CREATE_DATE" IS 'Ngày giờ tạo';
   COMMENT ON COLUMN "QLDV_UNIONS_MEMBER"."UPDATE_USER" IS 'Người cập nhật';
   COMMENT ON COLUMN "QLDV_UNIONS_MEMBER"."UPDATE_DATE" IS 'Ngày giờ cập nhật';
   COMMENT ON COLUMN "QLDV_UNIONS_MEMBER"."REASON_NOT_APP" IS 'Lý do từ chối duyệt';
   COMMENT ON COLUMN "QLDV_UNIONS_MEMBER"."BAR_CODE_USER" IS 'Bar code cho th viên đoàn';
   COMMENT ON COLUMN "QLDV_UNIONS_MEMBER"."BAR_CODE_COMPUTER" IS 'Bar code cho may tinh';
   COMMENT ON TABLE "QLDV_UNIONS_MEMBER"  IS 'Danh sách thành viên của đối tác';
--------------------------------------------------------
--  DDL for Index UNIONS_MEMBER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "QLDV_UNIONS_MEMBER_PK" ON "QLDV_UNIONS_MEMBER" ("UNION_MEMBER_ID");
--------------------------------------------------------
--  Constraints for Table UNIONS_MEMBER
--------------------------------------------------------

  ALTER TABLE "QLDV_UNIONS_MEMBER" MODIFY ("UNION_MEMBER_ID" NOT NULL ENABLE);
  ALTER TABLE "QLDV_UNIONS_MEMBER" MODIFY ("UNION_ID" NOT NULL ENABLE);
  ALTER TABLE "QLDV_UNIONS_MEMBER" MODIFY ("FULL_NAME" NOT NULL ENABLE);
  ALTER TABLE "QLDV_UNIONS_MEMBER" MODIFY ("NATIONAL_ID" NOT NULL ENABLE);
  ALTER TABLE "QLDV_UNIONS_MEMBER" ADD CONSTRAINT "QLDV_UNIONS_MEMBER_PK" PRIMARY KEY ("UNION_MEMBER_ID") USING INDEX  ENABLE;
