SELECT
  T1.UNION_MEMBER_ID unionMemberId,
  T1.FULL_NAME       fullName,
  T1.MEMBER_ID       memberId,
  T1.MEMBER_TYPE     memberType,
  T1.NATIONAL_ID     nationalId,
  T1.LAPTOP_ID       laptopId,
  T5.PARTNER_NAME    unionName,
  T2.FILE_ID         fileIdCMT,
  T3.FILE_ID         fileIdComputer
FROM QLDV_UNIONS_MEMBER T1
  LEFT JOIN QLDV_FILES T2 ON (T1.UNION_MEMBER_ID = T2.GROUP_ID AND T2.GROUP_FILE = '2')
  LEFT JOIN QLDV_FILES T3 ON (T1.UNION_MEMBER_ID = T3.GROUP_ID AND T3.GROUP_FILE = '3')
  LEFT JOIN QLDV_UNIONS T4 ON T1.UNION_ID = T4.UNION_ID
  LEFT JOIN QLDV_PARTNER T5 ON T4.PARTNER_ID = T5.PARTNER_ID
WHERE T1.UNION_MEMBER_ID = :member_id