SELECT DISTINCT 
  PD.PROVINCE_CODE provinceCode,
  PD.PROVINCE_VNAME provinceVname
FROM BOC_REGION_MAP PD
WHERE PD.STATUS = 1 
AND PD.DISTRICT_CODE = :p_unit_code
ORDER BY NLSSORT(PD.PROVINCE_VNAME, 'nls_sort = Vietnamese')