SELECT
  ROW_NUMBER() OVER (ORDER BY NLSSORT(kvCode, 'nls_sort = Vietnamese')) AS kvId,
  kvCode,
  kvName
FROM (
  SELECT DISTINCT
    CL.PROVINCE_CODE kvCode,
    CL.PROVINCE_NAME kvName
  FROM CATA_LOCATION CL
  WHERE CL.STATUS = 1 OR CL.STATUS = 2
  UNION
  SELECT DISTINCT
    CL.DISTRICT_CODE kvCode,
    CL.DISTRICT_NAME kvName
  FROM CATA_LOCATION CL
  WHERE CL.STATUS = 1 AND CL.DISTRICT_CODE IS NOT NULL
)
order by NLSSORT(kvCode, 'nls_sort = Vietnamese')