SELECT
  BUS.USER_ID userId
FROM BOC_USER BUS
INNER JOIN BOC_UNIT_USER BUU ON BUU.USER_ID = BUS.USER_ID
INNER JOIN BOC_UNIT BUN ON BUN.UNIT_ID = BUU.UNIT_ID
WHERE BUS.COMPANY = :company AND BUS.POSITION = :position AND BUN.UNIT_ID = :unitId
