SELECT 
  BR.ROLE_ID roleId,
  BR.ROLE_CODE roleCode,
  BR.ROLE_NAME roleName,
  BR.STATUS status,
  BR.PARENT_ROLE_ID parentRoleId
FROM BOC_ROLE BR
INNER JOIN BOC_ROLE_USER BRU ON BRU.ROLE_ID = BR.ROLE_ID
INNER JOIN BOC_USER BU ON BU.USER_ID = BRU.USER_ID
WHERE BU.USER_NAME = :userName