--------------------------------------------------------
--  File created - Tuesday-July-31-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BOC_ROLE_TARGET
--------------------------------------------------------

  CREATE TABLE "BOC_ROLE_TARGET" ("ROLE_TARGET_ID" NUMBER, "ROLE_TARGET_NAME" VARCHAR2(200), "ROLE_TARGET_CODE" VARCHAR2(200), "STATUS" NUMBER, "PARENT_ROLE_TARGET_ID" VARCHAR2(20)) 

   COMMENT ON COLUMN "BOC_ROLE_TARGET"."ROLE_TARGET_ID" IS 'Id của quyền mục tiêu'
   COMMENT ON COLUMN "BOC_ROLE_TARGET"."ROLE_TARGET_NAME" IS 'Tên quyền mục tiêu'
   COMMENT ON COLUMN "BOC_ROLE_TARGET"."ROLE_TARGET_CODE" IS 'Mã quyền mục tiêu'
   COMMENT ON COLUMN "BOC_ROLE_TARGET"."STATUS" IS 'Trạng thái'
   COMMENT ON COLUMN "BOC_ROLE_TARGET"."PARENT_ROLE_TARGET_ID" IS 'Id của quyền cha'
REM INSERTING into BOC_ROLE_TARGET
SET DEFINE OFF;
Insert into BOC_ROLE_TARGET (ROLE_TARGET_ID,ROLE_TARGET_NAME,ROLE_TARGET_CODE,STATUS,PARENT_ROLE_TARGET_ID) values (1,'Doanh thu','REVEUNE',1,null);
Insert into BOC_ROLE_TARGET (ROLE_TARGET_ID,ROLE_TARGET_NAME,ROLE_TARGET_CODE,STATUS,PARENT_ROLE_TARGET_ID) values (2,'Tỷ lệ thu tiền điện','ELECTRIC_PAYABLE_RATE',1,'1');
Insert into BOC_ROLE_TARGET (ROLE_TARGET_ID,ROLE_TARGET_NAME,ROLE_TARGET_CODE,STATUS,PARENT_ROLE_TARGET_ID) values (3,'Giá bán bình quân','AVG_SELLING_PRICE',1,'1');
Insert into BOC_ROLE_TARGET (ROLE_TARGET_ID,ROLE_TARGET_NAME,ROLE_TARGET_CODE,STATUS,PARENT_ROLE_TARGET_ID) values (4,'Tổn thất điện','LOSS_ELECTRIC',1,null);
Insert into BOC_ROLE_TARGET (ROLE_TARGET_ID,ROLE_TARGET_NAME,ROLE_TARGET_CODE,STATUS,PARENT_ROLE_TARGET_ID) values (5,'Điện thương phẩm','ELECTRIC_COMMERCIAL',1,'1');
Insert into BOC_ROLE_TARGET (ROLE_TARGET_ID,ROLE_TARGET_NAME,ROLE_TARGET_CODE,STATUS,PARENT_ROLE_TARGET_ID) values (6,'Chăm sóc khách hàng','CUSTOMER_CARE',1,null);
Insert into BOC_ROLE_TARGET (ROLE_TARGET_ID,ROLE_TARGET_NAME,ROLE_TARGET_CODE,STATUS,PARENT_ROLE_TARGET_ID) values (7,'Tỷ lệ phiếu yêu cầu xử lý quá hạn','RATE_REQUEST_OVERDUE_PROCESSING',1,'6');
Insert into BOC_ROLE_TARGET (ROLE_TARGET_ID,ROLE_TARGET_NAME,ROLE_TARGET_CODE,STATUS,PARENT_ROLE_TARGET_ID) values (8,'Tỷ lệ phiếu yêu cầu nhiều lần','RATE_REQUEST_MULTIPLE',1,'6');
Insert into BOC_ROLE_TARGET (ROLE_TARGET_ID,ROLE_TARGET_NAME,ROLE_TARGET_CODE,STATUS,PARENT_ROLE_TARGET_ID) values (9,'Chỉ tiêu tổn thất điện năng khối điện lực','LOSS_ELECTRIC_POWER',1,'4');
Insert into BOC_ROLE_TARGET (ROLE_TARGET_ID,ROLE_TARGET_NAME,ROLE_TARGET_CODE,STATUS,PARENT_ROLE_TARGET_ID) values (10,'Chỉ tiêu tổn thất điện năng lũy kế khối điện lực','LOSS_ELECTRIC_POWER_ACCUMULATED',1,'4');
Insert into BOC_ROLE_TARGET (ROLE_TARGET_ID,ROLE_TARGET_NAME,ROLE_TARGET_CODE,STATUS,PARENT_ROLE_TARGET_ID) values (11,'Độ tin cậy cung cấp điện','TRUST_PROVIDE',1,null);
Insert into BOC_ROLE_TARGET (ROLE_TARGET_ID,ROLE_TARGET_NAME,ROLE_TARGET_CODE,STATUS,PARENT_ROLE_TARGET_ID) values (12,'Độ tin cậy cung cấp điện SAIDI khối cao thế','TRUST_PROVIDE_SAIDI',1,'11');
Insert into BOC_ROLE_TARGET (ROLE_TARGET_ID,ROLE_TARGET_NAME,ROLE_TARGET_CODE,STATUS,PARENT_ROLE_TARGET_ID) values (13,'Suất sự cố mạng lưới 110kV','NETWORK_PROBLEM_110',1,null);
Insert into BOC_ROLE_TARGET (ROLE_TARGET_ID,ROLE_TARGET_NAME,ROLE_TARGET_CODE,STATUS,PARENT_ROLE_TARGET_ID) values (14,'Chỉ tiêu về suất sự cố đường dây 110kV kéo dài','NETWORK_PROBLEM_110_1',1,'13');
Insert into BOC_ROLE_TARGET (ROLE_TARGET_ID,ROLE_TARGET_NAME,ROLE_TARGET_CODE,STATUS,PARENT_ROLE_TARGET_ID) values (15,'Chỉ tiêu về suất sự cố trạm biến áp 110kV','NETWORK_PROBLEM_110_3',1,'13');
--------------------------------------------------------
--  DDL for Index BOC_ROLE_TARGET_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOC_ROLE_TARGET_PK" ON "BOC_ROLE_TARGET" ("ROLE_TARGET_ID")
--------------------------------------------------------
--  Constraints for Table BOC_ROLE_TARGET
--------------------------------------------------------

  ALTER TABLE "BOC_ROLE_TARGET" MODIFY ("ROLE_TARGET_ID" NOT NULL ENABLE)
  ALTER TABLE "BOC_ROLE_TARGET" MODIFY ("STATUS" NOT NULL ENABLE)
  ALTER TABLE "BOC_ROLE_TARGET" ADD CONSTRAINT "BOC_ROLE_TARGET_PK" PRIMARY KEY ("ROLE_TARGET_ID") USING INDEX  ENABLE
