--------------------------------------------------------
--  File created - Tuesday-July-31-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BOC_MODULE
--------------------------------------------------------

  CREATE TABLE "BOC_MODULE" ("BOC_MODULE_ID" VARCHAR2(100), "MODULE_NAME" VARCHAR2(200), "MODULE_GROUP" VARCHAR2(50), "JSON_PARAM" VARCHAR2(1000), "SERVICE" VARCHAR2(30)) 

   COMMENT ON COLUMN "BOC_MODULE"."BOC_MODULE_ID" IS 'Mã module'
   COMMENT ON COLUMN "BOC_MODULE"."MODULE_NAME" IS 'Tên module'
   COMMENT ON COLUMN "BOC_MODULE"."MODULE_GROUP" IS 'Nhóm module'
   COMMENT ON COLUMN "BOC_MODULE"."JSON_PARAM" IS 'Tham số dạng JSON cho module'
   COMMENT ON COLUMN "BOC_MODULE"."SERVICE" IS 'Service lấy dữ liệu'
REM INSERTING into BOC_MODULE
SET DEFINE OFF;
Insert into BOC_MODULE (BOC_MODULE_ID,MODULE_NAME,MODULE_GROUP,JSON_PARAM,SERVICE) values ('ELT_PAY_RATE','Xu thế Tỷ lệ thu tiền điện','ELECTRIC_PAYABLE_RATE',null,'CHART_XT');
Insert into BOC_MODULE (BOC_MODULE_ID,MODULE_NAME,MODULE_GROUP,JSON_PARAM,SERVICE) values ('ELT_PAY_ACCUMULATED','Xu thế lũy kế','ELECTRIC_PAYABLE_RATE',null,'CHART_LK');
Insert into BOC_MODULE (BOC_MODULE_ID,MODULE_NAME,MODULE_GROUP,JSON_PARAM,SERVICE) values ('ELT_PAY_REGION_COMPARE','So sánh địa bàn','ELECTRIC_PAYABLE_RATE',null,'CHART_REGION');
Insert into BOC_MODULE (BOC_MODULE_ID,MODULE_NAME,MODULE_GROUP,JSON_PARAM,SERVICE) values ('AVG_SELL_PRICE','Xu thế giá bán bình quân','AVG_SELLING_PRICE',null,'CHART_XT');
Insert into BOC_MODULE (BOC_MODULE_ID,MODULE_NAME,MODULE_GROUP,JSON_PARAM,SERVICE) values ('AVG_SELL_PRICE_ACCUMULATED','Xu thế lũy kế','AVG_SELLING_PRICE',null,'CHART_LK');
Insert into BOC_MODULE (BOC_MODULE_ID,MODULE_NAME,MODULE_GROUP,JSON_PARAM,SERVICE) values ('AVG_SELL_PRICE_REGION_COMPARE','So sánh địa bàn','AVG_SELLING_PRICE',null,'CHART_REGION');
Insert into BOC_MODULE (BOC_MODULE_ID,MODULE_NAME,MODULE_GROUP,JSON_PARAM,SERVICE) values ('RATE_RQ_OVER_PRC','Xu thế Tỷ lệ phiếu yêu cầu xử lý quá hạn','RATE_REQUEST_OVERDUE_PROCESSING',null,'CHART_XT');
Insert into BOC_MODULE (BOC_MODULE_ID,MODULE_NAME,MODULE_GROUP,JSON_PARAM,SERVICE) values ('RATE_RQ_OVER_PRC_ACCUMLATED','Xu thế lũy kế','RATE_REQUEST_OVERDUE_PROCESSING',null,'CHART_LK');
Insert into BOC_MODULE (BOC_MODULE_ID,MODULE_NAME,MODULE_GROUP,JSON_PARAM,SERVICE) values ('RATE_RQ_OVER_PRC_REGION_COMPARE','So sánh địa bàn','RATE_REQUEST_OVERDUE_PROCESSING',null,'CHART_REGION');
Insert into BOC_MODULE (BOC_MODULE_ID,MODULE_NAME,MODULE_GROUP,JSON_PARAM,SERVICE) values ('RATE_REQ_MULTI','Xu thế Tỷ lệ phiếu yêu cầu nhiều lần','RATE_REQUEST_MULTIPLE',null,'CHART_XT');
Insert into BOC_MODULE (BOC_MODULE_ID,MODULE_NAME,MODULE_GROUP,JSON_PARAM,SERVICE) values ('RATE_REQ_MULTI_ACCUMULATED','Xu thế lũy kế','RATE_REQUEST_MULTIPLE',null,'CHART_LK');
Insert into BOC_MODULE (BOC_MODULE_ID,MODULE_NAME,MODULE_GROUP,JSON_PARAM,SERVICE) values ('RATE_REQ_MULTI_REGION_COMPARE','So sánh địa bàn','RATE_REQUEST_MULTIPLE',null,'CHART_REGION');
Insert into BOC_MODULE (BOC_MODULE_ID,MODULE_NAME,MODULE_GROUP,JSON_PARAM,SERVICE) values ('TRUST_P_SAIDI_REGION_COMPARE','So sánh địa bàn','TRUST_PROVIDE_SAIDI',null,'CHART_REGION');
Insert into BOC_MODULE (BOC_MODULE_ID,MODULE_NAME,MODULE_GROUP,JSON_PARAM,SERVICE) values ('NETWORK_PR_110_1_REGION_COMPARE','So sánh địa bàn','NETWORK_PROBLEM_110_1',null,'CHART_REGION');
Insert into BOC_MODULE (BOC_MODULE_ID,MODULE_NAME,MODULE_GROUP,JSON_PARAM,SERVICE) values ('NETWORK_PR_110_3_REGION_COMPARE','So sánh địa bàn','NETWORK_PROBLEM_110_3',null,'CHART_REGION');
Insert into BOC_MODULE (BOC_MODULE_ID,MODULE_NAME,MODULE_GROUP,JSON_PARAM,SERVICE) values ('ELT_COM','Xu thế Điện thương phẩm','ELECTRIC_COMMERCIAL',null,'CHART_XT');
Insert into BOC_MODULE (BOC_MODULE_ID,MODULE_NAME,MODULE_GROUP,JSON_PARAM,SERVICE) values ('ELT_COM_ACCUMULATED','Xu thế lũy kế ','ELECTRIC_COMMERCIAL',null,'CHART_LK');
Insert into BOC_MODULE (BOC_MODULE_ID,MODULE_NAME,MODULE_GROUP,JSON_PARAM,SERVICE) values ('ELT_COM_REGION_COMPARE','So sánh địa bàn','ELECTRIC_COMMERCIAL',null,'CHART_REGION');
Insert into BOC_MODULE (BOC_MODULE_ID,MODULE_NAME,MODULE_GROUP,JSON_PARAM,SERVICE) values ('LOSS_ELT_POWER','Xu thế Chỉ tiêu tổn thất điện năng','LOSS_ELECTRIC_POWER',null,'CHART_XT');
Insert into BOC_MODULE (BOC_MODULE_ID,MODULE_NAME,MODULE_GROUP,JSON_PARAM,SERVICE) values ('LOSS_ELT_POWER_REGION_COMPARE','So sánh địa bàn','LOSS_ELECTRIC_POWER',null,'CHART_REGION');
Insert into BOC_MODULE (BOC_MODULE_ID,MODULE_NAME,MODULE_GROUP,JSON_PARAM,SERVICE) values ('LOSS_EP_ACCUMULATED','Xu thế Chỉ tiêu tổn thất điện năng lũy kế','LOSS_ELECTRIC_POWER_ACCUMULATED',null,'CHART_LK');
Insert into BOC_MODULE (BOC_MODULE_ID,MODULE_NAME,MODULE_GROUP,JSON_PARAM,SERVICE) values ('TRUST_P_SAIDI','Xu thế Độ tin cậy cung cấp điện SAIDI','TRUST_PROVIDE_SAIDI',null,'CHART_XT');
Insert into BOC_MODULE (BOC_MODULE_ID,MODULE_NAME,MODULE_GROUP,JSON_PARAM,SERVICE) values ('TRUST_P_SAIDI_ACCUMULATED','Xu thế Độ tin cậy lũy kế cung cấp điện SAIDI','TRUST_PROVIDE_SAIDI',null,'CHART_LK');
Insert into BOC_MODULE (BOC_MODULE_ID,MODULE_NAME,MODULE_GROUP,JSON_PARAM,SERVICE) values ('NETWORK_PR_110_1','Xu thế chỉ tiêu suất sự cố đường dây 110kV kéo dài','NETWORK_PROBLEM_110_1',null,'CHART_XT');
Insert into BOC_MODULE (BOC_MODULE_ID,MODULE_NAME,MODULE_GROUP,JSON_PARAM,SERVICE) values ('NETWORK_PR_110_1_ACCUMULATED','Xu thế chỉ tiêu suất sự cố lũy kế đường dây 110kV kéo dài','NETWORK_PROBLEM_110_1',null,'CHART_LK');
Insert into BOC_MODULE (BOC_MODULE_ID,MODULE_NAME,MODULE_GROUP,JSON_PARAM,SERVICE) values ('NETWORK_PR_110_3','Xu thế chỉ tiêu suất sự cố trạm biến áp 110kV ','NETWORK_PROBLEM_110_3',null,'CHART_XT');
Insert into BOC_MODULE (BOC_MODULE_ID,MODULE_NAME,MODULE_GROUP,JSON_PARAM,SERVICE) values ('NETWORK_PR_110_3_ACCUMULATED','Xu thế chỉ tiêu suất sự cố lũy kế trạm biến áp 110kV ','NETWORK_PROBLEM_110_3',null,'CHART_LK');
--------------------------------------------------------
--  DDL for Index BOC_MODULE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOC_MODULE_PK" ON "BOC_MODULE" ("BOC_MODULE_ID")
--------------------------------------------------------
--  Constraints for Table BOC_MODULE
--------------------------------------------------------

  ALTER TABLE "BOC_MODULE" MODIFY ("BOC_MODULE_ID" NOT NULL ENABLE)
  ALTER TABLE "BOC_MODULE" ADD CONSTRAINT "BOC_MODULE_PK" PRIMARY KEY ("BOC_MODULE_ID") USING INDEX  ENABLE
